name: Deploy with Doppler Secrets
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doppler CLI
        run: |
          # Install Doppler CLI
          curl -sLf --retry 3 https://downloads.doppler.com/install.sh | sh
          # Add Doppler CLI to PATH
          echo "$HOME/.doppler/bin" >> $GITHUB_PATH
      - name: Verify Doppler CLI Installation
        run: |
          # Confirm Doppler CLI is available
          doppler --version
      - name: Fetch and Verify Doppler Secrets
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          # Fetch API_KEY using Doppler CLI
          API_KEY=$(doppler secrets get API_KEY --plain)
          # Log last 4 digits to verify injection
          LAST_FOUR=${API_KEY: -4}
          echo "Doppler injected API_KEY ending in: $LAST_FOUR"
      - name: Simulate App Secret Usage
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          # Run a Node.js command to mimic app behavior
          doppler run -- node -e "console.log('API_KEY from app environment ending in: ' + process.env.API_KEY.slice(-4))"
