name: Deploy with Doppler Secrets
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to latest version for better compatibility
      - name: Install Doppler CLI
        run: curl -sLf --retry 3 https://downloads.doppler.com/install.sh | sh
      - name: Fetch and Verify Doppler Secrets
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          # Run a command with Doppler to inject secrets and capture API_KEY
          API_KEY=$(doppler secrets get API_KEY --plain)
          # Extract last 4 digits of API_KEY
          LAST_FOUR=${API_KEY: -4}
          echo "Doppler injected API_KEY ending in: $LAST_FOUR"
