name: Doppler Cloud Test

on: [push]

jobs:
  test-doppler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doppler CLI
        run: curl -sLf --retry 3 https://downloads.doppler.com/install.sh | sh

      - name: Inject secrets from Doppler
        run: doppler secrets download --no-file --format env >> $GITHUB_ENV
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Simulate app logic
        run: |
          echo "Using API key ending in: ${API_KEY: -4}"
